import { Inter } from 'next/font/google';
import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <div>
          <div
            style={{
              position: 'absolute',
              zIndex: '3',
              width: '100%',
              height: '175px',
            }}
          >
            <svg
              xmlns='http://www.w3.org/2000/svg'
              width='100%'
              height='180'
              viewBox='0 0 100% 178'
              fill='none'
            >
              <path
                d='M0 0H1920V88H1100C895.212 280 750 88 750 88C422.59 88 0 88 0 88V0Z'
                fill='white'
                style={{
                  filter: 'drop-shadow(1px 1px 5px rgba(5, 5, 5,0.514))',
                }}
              />
            </svg>
          </div>
          <div
            className='Header'
            style={{
              width: '100%',
              height: '88px',
              position: 'relative',
              backgroundColor: '#FFFFFF',
              zIndex: '4',
            }}
          >
            <div className='leftDiv'>
              <article className='Hell'>Home</article>
              <article className='Hell'>About Us</article>
              <article className='Hell'>Our Healing Center</article>
              <article className='Hell'>Healing Stories</article>
            </div>
            <div className='middleDiv'>
              <img
                src='/Rectangle 2.png'
                alt=''
              />
            </div>
            <div className='rightDiv'>
              <article className='Hell'>Program</article>
              <article className='Hell'>News & Media</article>
              <article className='Hell'>Online Programs</article>
              <article className=''>
                <button className='bookBtn'>Book Appointment</button>
              </article>
            </div>
          </div>
          {children}
        </div>
      </body>
    </html>
  );
}
